config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tags#index'
  resources :recipes do
    resources :foodstuffs
    resources :texts
  end
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foodstuff.rb
class Foodstuff < ApplicationRecord
  belongs_to :recipe

  validates :material, presence: true, length: { maximum: 20 }
  validates :quantity, presence: true, length: { maximum: 10 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attachment :main_image
  has_many :recipe_tag_relations, dependent: :destroy
  has_many :tags, through: :recipe_tag_relations, dependent: :destroy
  
  has_many :texts
  has_many :foodstuffs
  belongs_to :user
  validates :title, :details, :process, :main_image, presence: true
end

app/models/recipe_tag_relation.rb
class RecipeTagRelation < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tag_relations, dependent: :destroy
  has_many :recipes, through: :recipe_tag_relations
end

app/models/text.rb
class Text < ApplicationRecord
  attachment :text_image
  belongs_to :recipe

  validates :text,        presence: true
  validates :text_image,     presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password,        length: { minimum: 6 }, confirmation: true,  format: { with: /\A[a-zA-Z0-9]+\z/ }
  
  with_options presence: true do      
    validates :name        
    validates :profile
    validates :occupation
    validates :position
  end

  has_many :recipes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
end

app/controllers/foodstuffs_controller.rb
class FoodstuffsController < ApplicationController
  
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foodstuffs = Foodstuff.where(recipe_id: @recipe.id).order(:position)
    @foodstuff = Foodstuff.new
  end

  

  def create
    @foodstuff = Foodstuff.new(foodstuff_params)
    if @foodstuff.save
    redirect_to new_recipe_text_path( @foodstuff.recipe_id)
    else
      @recipe = @foodstuff.recipe
      @foodstuffs = @recipe.texts
      render :edit
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @foodstuffs = Foodstuff.where(recipe_id: @recipe.id).order(:position)
    @foodstuff = Foodstuff.new
  end


  
    def update
      @foodstuff = Foodstuff.find(params[:id])
      @foodstuffs = @recipe.texts.all
      @recipe = Recipe.find(params[:recipe_id])
      flash.now[:update] = 'UPDATE !' if @foodstuff.update(foodstuff_params)
    end
  
    private
    def foodstuff_params
      params.permit(:material, :quantity).merge(recipe_id: params[:recipe_id])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end

  def create
    
    @recipe = Recipe.new(recipe_params)
    @recipe.valid?
    if @recipe.save
      @recipe[:id]
      redirect_to new_recipe_foodstuff_path(@recipe.id)
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @text = Text.new
    @texts = @recipe.texts
    @foodstuff = Foodstuff.new
    @foodstuffs = @recipe.foodstuffs
  end



  def edit
    @recipe = Recipe.find(params[:id])
    @text = Text.new
    @texts = @recipe.texts
    @foodstuff = Foodstuff.new
    @foodstuffs = @recipe.foodstuffs
  end

  

    private
  def recipe_params
    params.require(:recipe).permit(:title, :process, :details, :main_image, tag_ids: []).merge(user_id: current_user.id)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.find(1)
    @tagss = Tag.find(2)
    @tagsss = Tag.find(3)
    @tagssss = Tag.find(4)
    @tagsssss = Tag.find(5)
    @tagssssss = Tag.find(6)
    @tagsssssss = Tag.find(7)
    @tagssssssss = Tag.find(8)
    @tagsssssssss = Tag.find(9)

    # @image = [french.1.jpg, french.2.jpg, french.3.jpg,
    #           japan.1.jpg, japan.2.jpg, japan.3.jpg,
    #           chinese.1.jpg, chinese.2.jpg ,chinese.3.jpg
    #         ]
  end

  def show
    @tag = Tag.find(params[:id])
    @recipe = Recipe.new
    @recipes = @tag.recipes
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foodstuffs = Foodstuff.where(recipe_id: @recipe.id)

    @texts = Text.where(recipe_id: @recipe.id).order(:position)
    @text = Text.new
  end




  def create
    @text = Text.new(text_params)
    if @text.save
      
      redirect_to recipe_path(@text.recipe_id), method: :get
    else
      @recipe = @text.recipe
      @texts = @recipe.texts
      render "recipes/show"
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    redirect_to root_path if current_user.id != @recipe.user_id
    @recipe = Recipe.find(params[:recipe_id])
    @text = Text.new
    @texts = Text.where(recipe_id: @recipe.id).order(:position)
  end

  def update
    @text = Text.find(params[:id])
    @texts = @recipe.texts.all
    @recipe = Recipe.find(params[:recipe_id])
    flash.now[:update] = 'UPDATE !' if @text.update(text_params)
  end

  private
  def text_params
    params.require(:text).permit(:text, :text_image).merge(recipe_id: params[:recipe_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodstuffs_helper.rb
module FoodstuffsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/foodstuffs/edit.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @recipe.title %>
      </p>
      
      <div class="main_image">
         <%= attachment_image_tag @recipe, :main_image, class: :card_img  %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @recipe.details %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @recipe.process %>
          </p>
        </div>



<div class="prototype__comments">
          <% if user_signed_in?%>
            <%= form_with(model: [@recipe, @foodstuff], local: true) do |f| %>
              <%= form_with(model: [@recipe, @text], local: true) do |f| %>
              <div class="field">
                <%= f.label :material, "コメント" %><br />
                <%= f.text_field :material %>
                  <%= f.label :quantity, "コメント" %><br />
                <%= f.text_field :quantity %>
              </div>

              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %> 
          <% end %> 
          <ul class="comments_lists">
            <% if @foodstuff %>
           <% @foodstuffs.each do |foodstuff| %>
              <li class="comments_list">
              <p>
               <%= foodstuff.material %>
              <div class="prototype__image">
        <%= foodstuff.quantity %>
      </div>
              </p> 
              </li>
              <% end %>
             <% end %>
          </ul>
        </div>
 <% end %>

 </div>



        <div class="prototype__comments">
          <% if user_signed_in?%>
            <%= form_with(model: [@recipe, @text], local: true) do |f| %>
              <div class="field">
                <%= f.label :text, "コメント" %><br />
                <%= f.text_field :text %>
                  <%= f.label :text_image, "コメント" %><br />
                <%= f.attachment_field :text_image %>
              </div>

              
              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %> 
          <% end %> 
          <ul class="comments_lists">
            <% if @text %>
           <% @texts.each do |text| %>
              <li class="comments_list">
              <p>
               <%= text.text %>
              <div class="prototype__image">
         <%= attachment_image_tag text, :text_image, class: :card_img  %>
      </div>
              </p> 
              </li>
              <% end %>
             <% end %>
          </ul>
        </div>
    </div>
  </div>
</main>

app/views/foodstuffs/new.html.erb
<div class="form-wrapper">
  <div class="tag-inner">

    <div class="">
      <h2 class="page-heading">新規レシピ投稿</h2>       
  <%= form_with(model: @recipe, url: recipes_path, local: true) do |f| %>
 <div class="field">
   <%= f.label :process, "作り方" %><br />
    <p class="detail__message">
            <%= @recipe.process %>
          </p>
  </div>

  


  <div class="main-contents">
 <div class="image-content">
              <%= attachment_image_tag @recipe, :main_image %>
   </div>
   <div class="from-content">
     <div class="title-content">
       <div class="title-name">
         <p> 料理名 </p>
       </div>
     <div class="valu-name">
        <p><%= @recipe.title %></p>
       </div>
    </div>
    <div class="details-content">
    <div class="title-name">
         <p> 分量(何人前) </p>
          </div>   
        <div class="valu-name">
      <p> <%= @recipe.details %></p>
      </div>
    </div>    
<% end %>
<%= form_with(model: @text, url:  recipe_foodstuffs_path, local: true) do |f| %>
<div class="material-content">
  <div class="field">
    <%= f.label :material, "材料" %><br />
    <%= f.text_field :material %>
  </div>

   <div class="field">
    <%= f.label :quantity, "分量" %><br />
    <%= f.text_field :quantity %>
  </div>

</div>
  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>

<% end %>


</div>
</div>
    </div>
  </div>
</div>
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recetter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header-inner">
        <div class="logo">
          <img src="" />
        </div>
        <nav class="header-nav">
          <form class="form">
            <input type="search" class="form-input" placeholder="search" />
            <button class="form-button"><i class="fa fa-search"></i></button>
          </form>  
         <% if user_signed_in? %>
            <div class="nav__right"> 
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
               <%= link_to "New Proto",  new_recipe_path, class: :nav__btn %>
             </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
   
  <%= form_with(model: @recipe, url: recipes_path, local: true) do |f| %>

   

  <div class="field">
    <%= f.label :title, "料理名" %><br />
    <%= f.text_field :title %>
  </div>

   <div class="field">
    <%= f.label :main_image, "メインの画像" %><br />
    <%= f.file_field :main_image %>
  </div>


   <% 2.times do %>
     <%= f.fields_for :texts do |text| %>
       <%= text.text_field 'text' %>
         <div class="field">
           <%= f.label :main_image, "写真", class: "label" %>
           <%= f.attachment_field :main_image, class: "input" %>
         </div>
     <% end %>
   <% end %>

  <div class="field">
   <%= f.label :process, "材料" %><br />
    <%= f.text_area :process, class: :form__text %>
  </div>

  

  <div class="field">
    <%= f.label :material, "作り方" %><br />
    <%= f.text_area :material, class: :form__text %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>

  <div class="check_box">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
     <div>
       <%= tag.label do %>
         <%= tag.check_box %>
         <%= tag.text %>
       <% end %>
     </div>
   <% end %>
 </div>

<% end %>

app/views/recipes/_recipe.html.erb
    <div class="card">
      <div class="card__body">
       <%= attachment_image_tag recipe, :main_image, class: :card_img  %>
        </div>
          <%= link_to recipe.title, recipe_path(recipe.id), method: :get, class: :card__title%>
       </div> 
     </div>

   

app/views/recipes/edit.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @recipe.title %>
      </p>
      
      <div class="main_image">
         <%= attachment_image_tag @recipe, :main_image, class: :card_img  %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @recipe.details %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @recipe.process %>
          </p>
        </div>



<div class="prototype__comments">
          <% if user_signed_in?%>
            <%= form_with(model: [@recipe, @foodstuff], local: true) do |f| %>
              <%= form_with(model: [@recipe, @text], local: true) do |f| %>
              <div class="field">
                <%= f.label :material, "コメント" %><br />
                <%= f.text_field :material %>
                  <%= f.label :quantity, "コメント" %><br />
                <%= f.text_field :quantity %>
              </div>

              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %> 
          <% end %> 
          <ul class="comments_lists">
            <% if @foodstuff %>
           <% @foodstuffs.each do |foodstuff| %>
              <li class="comments_list">
              <p>
               <%= foodstuff.material %>
              <div class="prototype__image">
        <%= foodstuff.quantity %>
      </div>
              </p> 
              </li>
              <% end %>
             <% end %>
          </ul>
        </div>
 <% end %>

 </div>



        <div class="prototype__comments">
          <% if user_signed_in?%>
            <%= form_with(model: [@recipe, @text], local: true) do |f| %>
              <div class="field">
                <%= f.label :text, "コメント" %><br />
                <%= f.text_field :text %>
                  <%= f.label :text_image, "コメント" %><br />
                <%= f.attachment_field :text_image %>
              </div>

              
              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %> 
          <% end %> 
          <ul class="comments_lists">
            <% if @text %>
           <% @texts.each do |text| %>
              <li class="comments_list">
              <p>
               <%= text.text %>
              <div class="prototype__image">
         <%= attachment_image_tag text, :text_image, class: :card_img  %>
      </div>
              </p> 
              </li>
              <% end %>
             <% end %>
          </ul>
        </div>
    </div>
  </div>
</main>

app/views/recipes/new.html.erb
<div class="form-wrapper">
  <div class="tag-inner">
    <div class="">
      <h2 class="page-heading">新規レシピ投稿</h2>
       
  <%= form_with(model: @recipe, url: recipes_path, local: true) do |f| %>
  <div class="main-contents">
  <div class="image-content">
 
                <%= image_tag "french.1.jpg" %>
    <div class="field">
     
      <%= f.attachment_field :main_image %>
   </div>
   </div>

<div class="text-content">
  <div class="field">
    <%= f.label :title, "料理名" %><br />
    <%= f.text_field :title , class: :form_text%>
  </div>


  <div class="field">
    <%= f.label :details, "何人前" %><br />
    <%= f.text_area :details, class: :form_text %>
  </div>


<div class="check_box">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
     <li class="tag-list">
       <%= tag.label do %>
         <%= tag.check_box %>
         <%= tag.text %>
       <% end %>
     </li>
     
   <% end %>
 </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
</div>
</div>

  


 <div class="field">
   <%= f.label :process, "作り方" %><br />
    <%= f.text_area :process, class: :form_prosess %>
  </div>

  


<% end %>




    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @recipe.title %>
      </p>
      
      <div class="main_image">
         <%= attachment_image_tag @recipe, :main_image, class: :card_img  %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @recipe.details %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @recipe.process %>
          </p>
        </div>



<div class="prototype__comments">
   <% if user_signed_in?%>
            <%= form_with(model: [@recipe, @foodstuff], local: true) do |f| %>
              <div class="field">
                <%= f.label :material, "コメント" %><br />
                <%= f.text_area :material %>
                  <%= f.label :quantity, "コメント" %><br />
                <%= f.text_area :quantity %>
              </div>


              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %> 
        
          <ul class="comments_lists">
            <% if @foodstuff %>
           <% @foodstuffs.each do |foodstuff| %>
              <li class="comments_list">
              <p>
               <%= foodstuff.material %>
              <div class="prototype__image">
        <%= foodstuff.quantity %>
      </div>
              </p> 
              </li>
              <% end %>
             <% end %>
          </ul>
        </div>
 <% end %>

 </div>



        <div class="prototype__comments">
          <% if user_signed_in?%>
            <%= form_with(model: [@recipe, @text], local: true) do |f| %>
              <div class="field">
                <%= f.label :text, "コメント" %><br />
                <%= f.text_field :text %>
                  <%= f.label :text_image, "コメント" %><br />
                <%= f.attachment_field :text_image %>
              </div>

              
              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %> 
          <% end %> 
          <ul class="comments_lists">
            <% if @text %>
           <% @texts.each do |text| %>
              <li class="comments_list">
              <p>
               <%= text.text %>
              <div class="prototype__image">
         <%= attachment_image_tag text, :text_image, class: :card_img  %>
      </div>
              </p> 
              </li>
              <% end %>
             <% end %>
          </ul>
        </div>
    </div>
  </div>
</main>

app/views/tags/_tag.erb
<div class="tag-content">
  <div class="card__body">
  <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype.id), method: :get%>
    <%= link_to prototype.title, prototype_path(prototype.id), method: :get, class: :card__title%>
    <p class="card__summary">
      <%= prototype.catch_copy %>
    </p>
    <%= link_to prototype.user.name, user_path(prototype.user.id), class: :card__user %>
    
  </div> 
</div>
   

   

app/views/tags/show.html.erb
<main class="main">
  <div class="tag-inner">
    <div class='tag-name'>
       <%= @tag.name %>
    </div>   
      <div class="tag-contents">
        <% @recipes.each do |recipe| %>
          <div class="tag-content">
            <div class="card__body">
              <div class='tag-image'>
                <%= attachment_image_tag recipe, :main_image  %>
              </div>
            </div>
            <p class="card__summary">
              <%= link_to recipe.title, recipe_path(recipe.id), method: :get, class: :card__title%>
            </p>
          </div> 
        <% end %>
      </div>
    </div>
  </div>
</main>
 
 

 

app/views/texts/edit.html.erb
<div class="container" style="padding-bottom: 100px;">
	<span class="form-title">Edit Cooking</span>
	<div class="row" style="margin-top: 30px">
		<div class="col-lg-6 col-12">
			<%= attachment_image_tag @recipe, :recipe_image, format:"jpg",
				fallback:"logo.jpg", class:"recipe-image-show" %>
		</div>
		<div class="col-lg-6">
			<p style="border-bottom: 1px solid silver; font-size: 20px" >レシピ
				<%= link_to "編集", edit_recipe_path(@recipe), class:"btn btn-warning btn-sm",
					style:"margin-bottom:5px", data: {"turbolinks" => false} %>
			</p>
			<div class="row">
				<div class="col-lg-3 col-3"><p>レシピ名</p></div>
				<div class="col-lg-9 col-9"><p><%= @recipe.title %></p></div>
			</div>
			<div class="row">
				<div class="col-lg-3 col-3"><p>紹介文</p></div>
				<div class="col-lg-9 col-9"><p><%= @recipe.introduction %></p></div>
			</div>
			<div class="row">
				<div class="col-lg-3 col-3"><p>分量(何人前)</p></div>
				<div class="col-lg-9 col-9"><p><%= @recipe.amount %></p></div>
			</div>
			<p style="border-bottom: 1px solid silver; font-size: 20px;margin-top:20px" >材料
				<%= link_to "編集", edit_recipe_ingredients_path(@recipe), class:"btn btn-warning btn-sm",
					style:"margin-bottom:5px", data: {"turbolinks" => false} %>
			</p>
			<% if flash[:create] %>
			 	<div class="good-flash"><i class="fas fa-check-circle"></i>
			 		<%= flash[:create]%>
			 	</div>
			<% end %>
			<% @recipe.ingredients.each do |ingredient| %>
				<div class="row" style="margin-bottom: 10px">
					<div class="col-lg-5 col-5 font-md-sp">
						<%= ingredient.content %>
					</div>
					<div class="col-lg-7 col-7 font-md-sp">
						<%= ingredient.amount %>
					</div>
				</div>
			<% end %>
			</ul>
		</div>
	</div>

	<div class="row" style="padding-top: 30px">
		<div class="col-lg-12">
			<p style="border-bottom: 1px solid #F5F5F5; font-size: 20px" >作り方
				<span class="font-sm">:矢印で順番の入れ替え</span>
			</p>
			<div id="error_explanation"><%= render "layouts/error", {object: @cooking} %></div>
			<span class="newform_<%= @recipe.id %>">
				<%= render "newform", {cookings: @cookings, recipe: @recipe} %>
			</span>
 			<%= form_for(@cooking, url:recipe_cookings_path, remote: true) do |f| %>
				<div class="row" style="padding-top: 30px;border-top: 1px solid #F5F5F5">
					<div class="col-lg-1"></div>
					<div class="col-lg-9 col-12">
						<%= f.text_area :content, rows:"2",style:"width:100%",placeholder:"作り方を入力する", class:"input-form" %>
					</div>
					<div class="col-lg-2 col-2">
						<%= f.hidden_field :recipe_id, value:@recipe.id %>
						<%= f.submit "追加", class:"btn btn-warning submit-btn-sm" %>
					</div>
				</div>
			<% end %>
			<div style="text-align: center; margin-top: 50px">

				<% if @recipe.ingredients.empty? %>
					<%= link_to "保存する", edit_recipe_ingredients_path(@recipe),class:"btn btn-warning",
						style:"padding: 5px 30px" %>

				<% elsif @recipe.recipe_status == "完成" or @recipe.recipe_status == "未入力あり" or
						 @recipe.recipe_status == "準備中" %>
					<%= link_to "戻る",recipe_path(@recipe), class:"btn btn-warning" %>

				<% else %>
					<%= form_with(url: recipe_path(@recipe),remote: true,  method: :patch) do |f| %>
						<%= f.hidden_field :recipe_status, value:"完成" %>
						<%= f.submit "投稿する", class:"btn btn-warning submit-btn" %>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/texts/new.html.erb
<div class="form-wrapper">
  <div class="tag-inner">

    <div class="">
      <h2 class="page-heading">新規レシピ投稿</h2>       
  <%= form_with(model: @recipe, url: recipes_path, local: true) do |f| %>
 <div class="field">
   <%= f.label :process, "作り方" %><br />
 <p class="detail__message">
            <%= @recipe.process %>
          </p>
  </div>  
  <div class="main-contents">
    <div class="image-content">
      <%= attachment_image_tag @recipe, :main_image %>
   </div>
   <div class="from-content">
     <div class="title-content">
       <div class="title-name">
         <p> 料理名 </p>
       </div>
     <div class="valu-name">
        <p><%= @recipe.title %></p>
       </div>
    </div>
    <div class="details-content">
    <div class="title-name">
         <p> 分量(何人前) </p>
          </div>   
        <div class="valu-name">
      <p> <%= @recipe.details %></p>
      </div>
    </div>    
<% end %>
     <div class="title-content">
       <% @foodstuffs.each do |foodstuff| %>
         <div class="title-name">
           <p><%= foodstuff.material %></p> 
         </div>
         <div class="valu-name">
           <%= foodstuff.quantity %>
         </div>
        <% end %>
     </div>
</div>
</div>

<%= form_with(model: @text, url:  recipe_texts_path, local: true) do |f| %>
  <div class="field">
    <%= f.label :text, "画像のコメント" %><br />
    <%= f.text_field :text %>
  </div>
   <div class="field">
    <%= f.label :text_image, "詳細の画像" %><br />
    <%= f.attachment_field :text_image %>
  </div>
  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>
    </div>
  </div>
</div>